export const colors = {
    water: "bg-gradient-to-b from-cyan-300 to-blue-400",
    fire: "bg-gradient-to-b from-orange-300 to-red-400",
    grass: "bg-gradient-to-b from-lime-300 to-green-400",
    electric: "bg-gradient-to-b from-amber-200 to-yellow-400",
    psychic: "bg-gradient-to-b from-fuchsia-300 to-fuchsia-500",
    normal: "bg-gradient-to-b from-neutral-200 to-neutral-400",
    bug: "bg-gradient-to-b from-amber-200 to-green-400",
    poison: "bg-gradient-to-b from-violet-300 to-purple-500",
    ground: "bg-yellow-300",
    fairy: "bg-pink-300",
    fighting: "bg-red-300",
    rock: "bg-yellow-300",
    ghost: "bg-gradient-to-b from-purple-300 to-fuchsia-500",
    ice: "bg-blue-300",
    dragon: "bg-red-300",
    dark: "bg-gradient-to-b from-slate-400 to-slate-700",
    steel: "bg-gray-300",
    flying: "bg-blue-300"
}