export const colors = {
    water: "bg-gradient-to-r from-cyan-300 to-blue-500",
    fire: "bg-gradient-to-r from-orange-300 to-red-500",
    grass: "bg-gradient-to-r from-lime-300 to-green-500",
    electric: "bg-gradient-to-r from-amber-200 to-orange-400",
    psychic: "bg-gradient-to-r from-purple-300 to-fuchsia-500",
    normal: "bg-gradient-to-r from-stone-300 to-neutral-500",
    bug: "bg-gradient-to-r from-amber-200 to-green-500",
    poison: "bg-gradient-to-r from-violet-300 to-purple-500",
    ground: "bg-gradient-to-r from-amber-700 to-yellow-900",
    fairy: "bg-gradient-to-r from-fuchsia-200 to-pink-500",
    fighting: "bg-gradient-to-r from-amber-500 to-orange-700",
    rock: "bg-gradient-to-r from-yellow-700 to-stone-700",
    ghost: "bg-gradient-to-r from-violet-300 to-indigo-500",
    ice: "bg-gradient-to-r from-cyan-200 to-sky-500",
    dragon: "bg-gradient-to-r from-rose-500 to-blue-500",
    dark: "bg-gradient-to-r from-slate-400 to-slate-700",
    steel: "bg-gradient-to-r from-slate-500 to-sky-800",
    flying: "bg-gradient-to-r from-blue-200 to-sky-500"
}